name: Publish to Registry and pull image

on: [release]


jobs:
  build_and_push_to_ghcr:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses:  actions/checkout@v3

      - name: Push Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: montenegroit/events
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: ${{ steps.meta.outputs.tags }}
          dockerfile: ./Dockerfile

  deploy:
    needs: build_and_push_to_ghcr
    runs-on: ubuntu-latest
    steps:
    - name: Docker down, pull and up remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ${{ secrets.BACKEND_PATH }}
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
