name : CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install -r requirements.txt

      - name: Linter & application tests
        run: |
          python -m black .
          cd src/
          python -m pytest
    
      
